# Site settings
title: REFLEX
email: your-email@domain.com
url: https://tennisparty.github.io/grayscale-theme/
#added below
baseurl: /grayscale-theme
description: "A nocturnal wildlife camera designed specifically for recording bat roosts in trees. The camera detects ultra-fast motion events at night and records bats emerging and re-entering from tree roosts."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: REFLEX wildlife

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/SBootstrap
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket
    url: http://bitbucket.org/jekyll
  - title: github
    url: https://github.com/IronSummitMedia/startbootstrap

# Build settings
markdown: kramdown
permalink: pretty
